---
title: "R_Notebook"
output: html_notebook
---


## Data Frame

```{r}

df <- data.frame(store_no = c(1:5),neighborhood = c("a","b","c","d","e"),profits = c(60,50,61,72,84))
df

str(df)

summary(df)

ncol(df)
nrow(df)

dim(df)


df2 <- data.frame(store_no = c(1:5),gecmis = c(2,4,5,3,6),per_sayisi = c(23,43,21,11,13))


merge(df,df2,all = TRUE)

df <- merge(df,df2,by = "store_no")

cbind(df,df2)

```

```{r}
df$store_no
df$profits
df$gecmis

df$new_variable <- c(12,45,23,55,77)
df$new_product <- c("shoe","bag","tshirt","shirt","suit")

#if we write df$new_product <- NULL that means new_product is gonna be deleted from the dataframe



df$per_profit <- df$new_variable/df$per_sayisi
df

```
### Turning a matrix into a data frame

```{r}
m <- matrix(1:9,nrow = 3,ncol = 3,byrow = TRUE)
m

df_m <- as.data.frame(m)
df_m

is.data.frame(df_m)

```

### Dataframe element operations

```{r}
install.packages("ggplot2")
library(ggplot2)

mpg

data.frame(mpg$manufacturer,mpg$model)


mpg[1,1]

mpg[1:3,]

mpg[mpg$manufacturer == "audi" & mpg$cyl == 6,]



```
## Lists and Tibbles

```{r}

l <- list("Super","Universe",1:10,FALSE)

l2 <- list(l,l)
l2


a <- list(1:10)
a <- unlist(a)
a

```














