---
title: "Lesson 2,3"
output: html_notebook
---

```{r}
a <- rep(1:2,3)
is.vector(a)
typeof(a)

a <- "Arda"

a <- c("Arda","Can","Ayse","Fatma","Deniz")
is.vector(a)
```
### Combaning Vectors

```{r}
a <- 1:10
b <- 2:11

a+b
a*b
c(a,b)

rbind(a,b)

cbind(a,b)
```
### Index of Vector and Choosing Element

```{r}
v <- 14:85
v[4]

v[10:20]

v[c(32,52,14,2)]
v[v>70]
v[v<20]
v[v>50 & v<60]
```
### Matrixs

```{r}
v1 <- c(3,4,5,6,7)
v2 <- c(4,2,6,7,5)
v3 <- c(3,5,7,4,8)
v4 <- c(5,2,6,8,8)

matrix1 <- cbind(v1,v2,v3,v4)
is.matrix(matrix1)

matrix1

matrix(nrow = 3,ncol = 3,1:9)

matrix(1:4,2,2)

matrix(1:9,nrow = 3,ncol = 3,byrow = TRUE)

matrix(c(10,14,21,74,88,13,11,31),nrow = 2,ncol = 4)

matrix(c(10,75,66,14,23,21,74,15,32,18),nrow = 2,
       ncol = 5,byrow = TRUE,dimnames = list(c("first","second"),c("first","second","third","fourth","fifth")))

m <- matrix(c(10,75,66,14,23,21,74,15,32,18),nrow = 2,
       ncol = 5,byrow = TRUE,dimnames = list(c("first","second"),c("first","second","third","fourth","fifth")))

m <- matrix(c(10,75,66,14,23,21,74,15,32,18),nrow = 2,ncol = 5,byrow = TRUE)

colnames(m) <- c("First","Second","Third","Fourth","Fifth")
rownames(m) <- c("First","Second")

m


m[1:2]
m[2:4]


dim(m)
```
### Combaning Matrixes

```{r}
MA <- rnorm(16,0,1)
MA <- matrix(MA,nrow = 4,ncol = 4)

MB <- rnorm(16,90,10)
MB <- matrix(MB,nrow = 4,ncol = 4)

rbind(MA,MB)

cbind(MA,MB)

```






















